package com.convertx.converters;
import com.convertx.core.Converter;import com.convertx.exceptions.ConversionException;import com.convertx.model.FileFormat;import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.dataformat.xml.XmlMapper;import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.io.*;import java.util.*;
public class DataConverter implements Converter{
 private final FileFormat a,b;public DataConverter(FileFormat a,FileFormat b){this.a=a;this.b=b;}public boolean supports(FileFormat x,FileFormat y){return x==a&&y==b;}
 public void convert(Path in,Path out)throws ConversionException{try{
  if(a==FileFormat.CSV&&b==FileFormat.JSON)csvJson(in,out);else if(a==FileFormat.JSON&&b==FileFormat.CSV)jsonCsv(in,out);else if(a==FileFormat.CSV&&b==FileFormat.XML)csvXml(in,out);else if(a==FileFormat.JSON&&b==FileFormat.XML)jsonXml(in,out);else if(a==FileFormat.XML&&b==FileFormat.JSON)xmlJson(in,out);else if(a==FileFormat.CSV&&b==FileFormat.XLSX)csvXlsx(in,out);else if(a==FileFormat.XLSX&&b==FileFormat.CSV)xlsxCsv(in,out);else throw new ConversionException("Unsupported data conversion.");
 }catch(Exception e){if(e instanceof ConversionException x)throw x;throw new ConversionException("Data conversion failed.",e);}}
 List<String[]> rows(Path p)throws IOException{List<String[]>r=new ArrayList<>();try(BufferedReader br=Files.newBufferedReader(p,StandardCharsets.UTF_8)){String s;while((s=br.readLine())!=null)r.add(s.split(",",-1));}return r;}
 void csvJson(Path i,Path o)throws IOException{List<String[]>r=rows(i);List<Map<String,String>>d=new ArrayList<>();if(r.isEmpty()){Files.writeString(o,"[]");return;}for(int k=1;k<r.size();k++){Map<String,String>m=new LinkedHashMap<>();for(int j=0;j<r.get(0).length;j++)m.put(r.get(0)[j],j<r.get(k).length?r.get(k)[j]:"");d.add(m);}new ObjectMapper().writerWithDefaultPrettyPrinter().writeValue(o.toFile(),d);}
 void jsonCsv(Path i,Path o)throws IOException{JsonNode n=new ObjectMapper().readTree(i.toFile());if(!n.isArray()||n.isEmpty()){Files.writeString(o,"");return;}List<String>h=new ArrayList<>();n.get(0).fieldNames().forEachRemaining(h::add);try(BufferedWriter w=Files.newBufferedWriter(o,StandardCharsets.UTF_8)){w.write(String.join(",",h));w.newLine();for(JsonNode x:n){for(int j=0;j<h.size();j++){if(j>0)w.write(",");w.write(x.path(h.get(j)).asText().replace(",",";"));}w.newLine();}}}
 void csvXml(Path i,Path o)throws IOException{List<String[]>r=rows(i);StringBuilder s=new StringBuilder("<data>\n");if(!r.isEmpty())for(int k=1;k<r.size();k++){s.append(" <row>\n");for(int j=0;j<r.get(0).length;j++)s.append("  <").append(r.get(0)[j].replaceAll("\\W","_")).append(">").append(j<r.get(k).length?r.get(k)[j]:"").append("</").append(r.get(0)[j].replaceAll("\\W","_")).append(">\n");s.append(" </row>\n");}Files.writeString(o,s.append("</data>\n").toString());}
 void jsonXml(Path i,Path o)throws IOException{new XmlMapper().writeValue(o.toFile(),new ObjectMapper().readTree(i.toFile()));}
 void xmlJson(Path i,Path o)throws IOException{new ObjectMapper().writerWithDefaultPrettyPrinter().writeValue(o.toFile(),new XmlMapper().readTree(i.toFile()));}
 void csvXlsx(Path i,Path o)throws IOException{try(XSSFWorkbook w=new XSSFWorkbook()){Sheet s=w.createSheet("Data");List<String[]>r=rows(i);for(int x=0;x<r.size();x++)for(int y=0;y<r.get(x).length;y++)s.createRow(x).createCell(y).setCellValue(r.get(x)[y]);try(OutputStream os=Files.newOutputStream(o)){w.write(os);}}}
 void xlsxCsv(Path i,Path o)throws IOException{try(Workbook w=WorkbookFactory.create(i.toFile());BufferedWriter out=Files.newBufferedWriter(o)){for(Row r:w.getSheetAt(0)){boolean f=true;for(Cell c:r){if(!f)out.write(",");f=false;out.write(c.toString().replace(",",";"));}out.newLine();}}}
}